# Generated by Django 3.0.7 on 2020-06-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.BigIntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=9)),
                ('datadecadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
