# Generated by Django 3.0.7 on 2020-06-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboracao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
