# Generated by Django 3.0.7 on 2020-06-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='marca',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
